//
// Created by wenha_000 on 2017-09-06.
//

#ifndef SHANGHAICITYTOURCARD_SHMETRO_COMMON_H
#define SHANGHAICITYTOURCARD_SHMETRO_COMMON_H

#ifndef UBYTE
#define UBYTE unsigned char
#endif

#endif //SHANGHAICITYTOURCARD_SHMETRO_COMMON_H
